services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - network
networks:
  network: null
